### PR TITLE
Change "Inviter" to "Promoter"

### PR DESCRIPTION
**Pull request by smowtenshi**
It's kind of old and misleading

### CODE REVIEW

**Comment by luni3359** [comment]
I agree that it's misleading, but in my opinion the whole field should just go. It made sense for it to exist before, but when was the last time you saw a site that told you who changed your member status?

**Comment by nonamethanks** [comment]
The field is there for accountability mostly, to immediately check who promoted someone, but admittedly it's just easier to check the feedbacks, since it doesn't show whether it was a promotion or a demotion and which privileges if any were added or removed. I agree it's a better idea to just remove it.

**Comment by evazion** [comment]
At this point it's a legacy field that only exists to track old users who were promoted before promotions were tracked in mod actions.

**Comment by evazion** [comment]
I'm going to add this field back. Even after clearing the inviter for all Gold/Plat self-upgrades, and for all users who have a feedback or a modaction listing who promoted them, there are still about 600 users for whom the inviter field is the only record of who promoted them.

**Comment by luni3359** [comment]
Could this at least become a moderator-only field? Do normal users need to see it?

**Pull request merged**
