### PR TITLE
README Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Separator]: https://raw.githubusercontent.com/ElectronicsArchiver/ElectronicsArchiver/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB/Separator.png

[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｃｏｍｍｅｎｄａｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<div align = center>

![Separator]

<br>
<br>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## Questions

- Is the repository's license supposed to be a BSD 2 Clause license?

<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  *Move wiki content into the `/docs/` folder.*

  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Separated topics

- Added censored preview

- Added quicklinks

- Unified badges to shield.io

- Added logo preview

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

<div align = center>

## ![Badge Robot]

<br>

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out

<br>

[![Button MarkedDown]][MarkedDown]

<br>
<br>

![Separator]

</div>

[Preview]: https://github.com/ElectronicsArchiver/danbooru

### CODE REVIEW

**Comment by evazion** [comment]
I don't think this formatting is necessary.

**Comment by ElectronicsArchiver** [comment]
> I don't think this formatting is necessary.

Necessary?

One also doesn't **need** to add a README, use folders, 
refactor code or style webpages with css.

That doesn't make it something that isn't 
useful or in general a positive thing.

**Comment by luni3359** [comment]
@ElectronicsArchiver Your formatting gives that corporate feel of "we're out of touch with reality" and makes for a worse user experience to force more clicks for the sake of change.

**Comment by ElectronicsArchiver** [comment]
<br>
<br>


> @ElectronicsArchiver Your formatting gives that corporate feel of "we're out of touch with reality" and makes for a worse user experience to force more clicks for the sake of change.

You call a hint of modern design, corporate?

<br>

> makes for a worse user experience to force more clicks

That's what you call content separation, a basic strategy 
to not drown the user with all the available information 
and allow them to choose what they came for.

<br>

> for the sake of change

For the sake of making things more easy to navigate.

<br>

If you actually cared so much about click reduction,
why would you use GitHub Wiki pages and at that,
leave the hub page empty and force the user to make
another click to find the only available installation?

<br>
<br>

**Comment by nonamethanks** [comment]
We appreciate the effort, but the danbooru is highly specialized software. The docs are fairly out of date, and need a complete rewrite, not this kind of graphical adjustment, so it would do more harm than good to present information of how to run this in a secondary page along with random outdated info.

**Pull request closed without merging**
