### PR TITLE
Change media asset links to use the same format

### PR DESCRIPTION
**Pull request by DCrow**
Implements #5624
Since there were many places where mostly the same format was used, moved all logic to a separate component for ease of use.

Also almost the same format is used in the media_assets page, but it links to the original file so I wasn't sure if it needed to be changed.
https://github.com/danbooru/danbooru/blob/09dd86b05a23b3740190ebfc9f375cd4306b051c/app/views/media_assets/show.html.erb#L26-L33

### CODE REVIEW

**Comment by nottalulah** [comment]
Using a whole component for something this small feels a bit overkill. Contrast something like [`link_to_user`](https://github.com/danbooru/danbooru/blob/09dd86b05a23b3740190ebfc9f375cd4306b051c/app/helpers/application_helper.rb#L245).

**Comment by DCrow** [comment]
@nottalulah I thought about doing a simple helper method, but helpers readme somewhat discouraged it 
https://github.com/danbooru/danbooru/blob/09dd86b05a23b3740190ebfc9f375cd4306b051c/app/helpers/README.md?plain=1#L13-L15

I can change it to a helper method if that's preferable.

**Comment by DCrow** [comment]
Changed component to a helper method.

**Comment by evazion** [comment]
image

The reason tooltips didn't have the filesize and type before was because there's not enough space for it. There's not enough room for everything and I think the size and type are the least important things here.

**Pull request merged**
