### PR TITLE
Allow Members to vote

### PR DESCRIPTION
**Pull request by evazion**
- [x] Allow Members to vote.
- [x] Make upvotes public by default, the same way favorites are public.
- [x] Change the "Private favorites" account setting to "Private favorites and upvotes".
- [x] Make private favorites, upvotes, and favgroups Gold-only features. Existing Members with private favorites or favgroups can keep them, but if they disable privacy then they will need a Gold account to re-enable it.
- [x] Add score/upvote/downvote buttons beneath thumbnails (optional; off by default).
- [x] Make it so you can click or hover over a post's score to see the list of upvoters, and the upvote-to-downvote ratio. Only public upvotes are visible; downvotes and private upvotes are shown as "hidden".
- [x] Remove the ability for banned users and restricted users to favorite posts. This is so banned or restricted users can't upvote posts using favorites.
- [x] Make upvote/downvote buttons visible to logged-out users.
- [x] Make it so the list of favorites is shown in the same way as the list of upvotes.
- [ ] Make it so when a post is heavily downvoted, it's automatically hidden, similar to blacklisting.
- [ ] Make it so when you downvote a post, it's automatically hidden for you, similar to blacklisting.
- [ ] Make it so when you upvote a post, it's automatically visible for you, even if it gets deleted.
- [ ] Add a way to easily blacklist frequently-blacklisted tags.

### CODE REVIEW

**Comment by evazion** [comment]
Screenshots:

image

image

**Comment by nonamethanks** [comment]
Just a reminder, admins need to be able to delete post votes like with comment votes, to combat sockpuppets.

**Comment by nottalulah** [comment]
Might be a good time to tackle issue #4640 as well.

**Comment by BrokenEagle** [comment]
Just my opinion, but the thumbnail score/vote UI should be standard aligned to the bottom of the thumbnail box, not the bottom of the thumbnail. That way, all of the controls will line up in a row. If needed, include a border around the thumbnail box so that it's clear which controls go to which thumbnail.

What is the DB timeout for getting post votes on the highest voted post? (3K+, [post # 3410029](https://danbooru.donmai.us/posts/3410029?), NSFW) Also, consider a more extreme case when everyone can vote, like 10K+, 50K+, and perhaps even 100K+. If these are likely to timeout, could the tooltip code just fetch like 100 entries at a time, and do something like infinite scrolling instead?

> Make it so when you downvote a post, it's automatically hidden for you, similar to blacklisting.
> Make it so when you upvote a post, it's automatically visible for you, even if it gets deleted.

Will this be done with Javascript, like additional steps to the blacklist code? Because otherwise it'll introduce an additional time penalty for DB queries, which will make things more likely to timeout for users. If it's the latter, can this be made optional? I'd rather choose for myself whether I want to add the `upvote:BrokenEagle98` and `downvote:BrokenEagle98` metatags myself.

> Add a way to easily blacklist frequently-blacklisted tags.

Will this be intelligently done, or will it just append tags as new entries on their own lines at the end of the blacklist? Because right now, every line in the blacklist requires O(n) time to process. In my own blacklist, I've been able to combine over a dozen tags on some of the lines, which drastically reduces the processing time. Or perhaps, will a separate blacklist be maintained, and it pretty much will act like a single giant OR line to the old blacklist?

**Comment by evazion** [comment]
Merging and deploying this to https://betabooru.donmai.us for now. Remaining issues will be addressed in future work.

>Just my opinion, but the thumbnail score/vote UI should be standard aligned to the bottom of the thumbnail box, not the bottom of the thumbnail. That way, all of the controls will line up in a row. If needed, include a border around the thumbnail box so that it's clear which controls go to which thumbnail.

This leads to big uneven gaps between the vote UI and the thumbnail, especially for wide images. This tends to look off in my opinion when there are irregular gaps between the UI and the thumbnail.

Most sites deal with this by cropping thumbnails to a fixed size, that way the UI always lines up. It's basically a choice between cropped thumbnails and perfect UI alignment, or uncropped thumbnails and imperfect UI alignment.

>What is the DB timeout for getting post votes on the highest voted post? (3K+, post # 3410029, NSFW) Also, consider a more extreme case when everyone can vote, like 10K+, 50K+, and perhaps even 100K+. If these are likely to timeout, could the tooltip code just fetch like 100 entries at a time, and do something like infinite scrolling instead?

Infinite scrolling is something we can do in the future. We already load the full list of favorites for the sidebar, even when the user doesn't look at it, which is even worse than loading the vote list in a tooltip. One of the changes here is to load favorites in a tooltip, that way we're at least not loading it in the initial pageload.

>Will this be done with Javascript, like additional steps to the blacklist code? Because otherwise it'll introduce an additional time penalty for DB queries, which will make things more likely to timeout for users. If it's the latter, can this be made optional? I'd rather choose for myself whether I want to add the upvote:BrokenEagle98 and downvote:BrokenEagle98 metatags myself.

Blacklists will probably have to go serverside, for various reasons, including this. Thumbnails would be given a `blacklisted`  class serverside, depending on whether they match one of your blacklist rules or not, then they can be hidden clientside in CSS.

We're already loading whether you've upvoted or downvoted the post, in order to render the vote buttons beneath the thumbnail correctly, so there's no extra penalty for showing or hiding posts based on your votes.

>Will this be intelligently done, or will it just append tags as new entries on their own lines at the end of the blacklist? Because right now, every line in the blacklist requires O(n) time to process. In my own blacklist, I've been able to combine over a dozen tags on some of the lines, which drastically reduces the processing time. Or perhaps, will a separate blacklist be maintained, and it pretty much will act like a single giant OR line to the old blacklist?

Handling blacklists serverside with a dedicated model for them will make this easier. Currently it's too hard to correctly add/remove tags to a user's blacklist without a bunch of messy Javascript.

**Comment by BrokenEagle** [comment]
Sounds good. Thanks for the reply. I hope the extra work for blacklist processing doesn't put too much additional strain on the server though.

Would turning on/off individual lines of a blacklist still be supported, or should we get rid of that? One benefit of no longer supporting on/off for individual lines is that you can early bail on posts which already have a line match, so that the remaining lines don't have to be checked. Lines could also be optimized by ordering them by the preponderance of post matches on Danbooru, putting the lines most likely to have a match first. This ordering could be done when the blacklist gets updated, and perhaps once every day/week/month if no changes have been done within that period. Removing the on/off for individual lines would also simplify the UI, necessitating only a single control to turn the entire blacklist on or off. For myself at least, I cannot recall the last time I've actually used the individual line controls. Anyways, just some food for thought.

**Pull request merged**
